
export const countries = [
  { value: "all", label: "All Countries" },
  // Regions
  { value: "EU", label: "🇪🇺 European Union", isRegion: true },
  { value: "USA", label: "🇺🇸 United States", isRegion: true },
  { value: "North America", label: "🌎 North America", isRegion: true },
  { value: "South America", label: "🌎 South America", isRegion: true },
  { value: "Asia", label: "🌏 Asia", isRegion: true },
  { value: "Africa", label: "🌍 Africa", isRegion: true },
  { value: "Oceania", label: "🌏 Oceania", isRegion: true },
  { value: "Middle East", label: "🌍 Middle East", isRegion: true },
  // Countries with region information
  { value: "Afghanistan", label: "Afghanistan", region: "Asia" },
  { value: "Albania", label: "Albania", region: "Europe" },
  { value: "Algeria", label: "Algeria", region: "Africa" },
  { value: "Andorra", label: "Andorra", region: "Europe" },
  { value: "Angola", label: "Angola", region: "Africa" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda", region: "North America" },
  { value: "Argentina", label: "Argentina", region: "South America" },
  { value: "Armenia", label: "Armenia", region: "Asia" },
  { value: "Australia", label: "Australia", region: "Oceania" },
  { value: "Austria", label: "Austria", region: "Europe" },
  { value: "Azerbaijan", label: "Azerbaijan", region: "Asia" },
  { value: "Bahamas", label: "Bahamas", region: "North America" },
  { value: "Bahrain", label: "Bahrain", region: "Middle East" },
  { value: "Bangladesh", label: "Bangladesh", region: "Asia" },
  { value: "Barbados", label: "Barbados", region: "North America" },
  { value: "Belarus", label: "Belarus", region: "Europe" },
  { value: "Belgium", label: "Belgium", region: "Europe" },
  { value: "Belize", label: "Belize", region: "North America" },
  { value: "Benin", label: "Benin", region: "Africa" },
  { value: "Bhutan", label: "Bhutan", region: "Asia" },
  { value: "Bolivia", label: "Bolivia", region: "South America" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", region: "Europe" },
  { value: "Botswana", label: "Botswana", region: "Africa" },
  { value: "Brazil", label: "Brazil", region: "South America" },
  { value: "Brunei", label: "Brunei", region: "Asia" },
  { value: "Bulgaria", label: "Bulgaria", region: "Europe" },
  { value: "Burkina Faso", label: "Burkina Faso", region: "Africa" },
  { value: "Burundi", label: "Burundi", region: "Africa" },
  { value: "Cabo Verde", label: "Cabo Verde", region: "Africa" },
  { value: "Cambodia", label: "Cambodia", region: "Asia" },
  { value: "Cameroon", label: "Cameroon", region: "Africa" },
  { value: "Canada", label: "Canada", region: "North America" },
  { value: "Central African Republic", label: "Central African Republic", region: "Africa" },
  { value: "Chad", label: "Chad", region: "Africa" },
  { value: "Chile", label: "Chile", region: "South America" },
  { value: "China", label: "China", region: "Asia" },
  { value: "Colombia", label: "Colombia", region: "South America" },
  { value: "Comoros", label: "Comoros", region: "Africa" },
  { value: "Congo", label: "Congo", region: "Africa" },
  { value: "Costa Rica", label: "Costa Rica", region: "North America" },
  { value: "Croatia", label: "Croatia", region: "Europe" },
  { value: "Cuba", label: "Cuba", region: "North America" },
  { value: "Cyprus", label: "Cyprus", region: "Europe" },
  { value: "Czech Republic", label: "Czech Republic", region: "Europe" },
  { value: "Denmark", label: "Denmark", region: "Europe" },
  { value: "Djibouti", label: "Djibouti", region: "Africa" },
  { value: "Dominica", label: "Dominica", region: "North America" },
  { value: "Dominican Republic", label: "Dominican Republic", region: "North America" },
  { value: "Ecuador", label: "Ecuador", region: "South America" },
  { value: "Egypt", label: "Egypt", region: "Africa" },
  { value: "El Salvador", label: "El Salvador", region: "North America" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", region: "Africa" },
  { value: "Eritrea", label: "Eritrea", region: "Africa" },
  { value: "Estonia", label: "Estonia", region: "Europe" },
  { value: "Eswatini", label: "Eswatini", region: "Africa" },
  { value: "Ethiopia", label: "Ethiopia", region: "Africa" },
  { value: "Fiji", label: "Fiji", region: "Oceania" },
  { value: "Finland", label: "Finland", region: "Europe" },
  { value: "France", label: "France", region: "Europe" },
  { value: "Gabon", label: "Gabon", region: "Africa" },
  { value: "Gambia", label: "Gambia", region: "Africa" },
  { value: "Georgia", label: "Georgia", region: "Asia" },
  { value: "Germany", label: "Germany", region: "Europe" },
  { value: "Ghana", label: "Ghana", region: "Africa" },
  { value: "Greece", label: "Greece", region: "Europe" },
  { value: "Grenada", label: "Grenada", region: "North America" },
  { value: "Guatemala", label: "Guatemala", region: "North America" },
  { value: "Guinea", label: "Guinea", region: "Africa" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", region: "Africa" },
  { value: "Guyana", label: "Guyana", region: "South America" },
  { value: "Haiti", label: "Haiti", region: "North America" },
  { value: "Honduras", label: "Honduras", region: "North America" },
  { value: "Hungary", label: "Hungary", region: "Europe" },
  { value: "Iceland", label: "Iceland", region: "Europe" },
  { value: "India", label: "India", region: "Asia" },
  { value: "Indonesia", label: "Indonesia", region: "Asia" },
  { value: "Iran", label: "Iran", region: "Middle East" },
  { value: "Iraq", label: "Iraq", region: "Middle East" },
  { value: "Ireland", label: "Ireland", region: "Europe" },
  { value: "Israel", label: "Israel", region: "Middle East" },
  { value: "Italy", label: "Italy", region: "Europe" },
  { value: "Ivory Coast", label: "Ivory Coast", region: "Africa" },
  { value: "Jamaica", label: "Jamaica", region: "North America" },
  { value: "Japan", label: "Japan", region: "Asia" },
  { value: "Jordan", label: "Jordan", region: "Middle East" },
  { value: "Kazakhstan", label: "Kazakhstan", region: "Asia" },
  { value: "Kenya", label: "Kenya", region: "Africa" },
  { value: "Kiribati", label: "Kiribati", region: "Oceania" },
  { value: "Kuwait", label: "Kuwait", region: "Middle East" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", region: "Asia" },
  { value: "Laos", label: "Laos", region: "Asia" },
  { value: "Latvia", label: "Latvia", region: "Europe" },
  { value: "Lebanon", label: "Lebanon", region: "Middle East" },
  { value: "Lesotho", label: "Lesotho", region: "Africa" },
  { value: "Liberia", label: "Liberia", region: "Africa" },
  { value: "Libya", label: "Libya", region: "Africa" },
  { value: "Liechtenstein", label: "Liechtenstein", region: "Europe" },
  { value: "Lithuania", label: "Lithuania", region: "Europe" },
  { value: "Luxembourg", label: "Luxembourg", region: "Europe" },
  { value: "Madagascar", label: "Madagascar", region: "Africa" },
  { value: "Malawi", label: "Malawi", region: "Africa" },
  { value: "Malaysia", label: "Malaysia", region: "Asia" },
  { value: "Maldives", label: "Maldives", region: "Asia" },
  { value: "Mali", label: "Mali", region: "Africa" },
  { value: "Malta", label: "Malta", region: "Europe" },
  { value: "Marshall Islands", label: "Marshall Islands", region: "Oceania" },
  { value: "Mauritania", label: "Mauritania", region: "Africa" },
  { value: "Mauritius", label: "Mauritius", region: "Africa" },
  { value: "Mexico", label: "Mexico", region: "North America" },
  { value: "Micronesia", label: "Micronesia", region: "Oceania" },
  { value: "Moldova", label: "Moldova", region: "Europe" },
  { value: "Monaco", label: "Monaco", region: "Europe" },
  { value: "Mongolia", label: "Mongolia", region: "Asia" },
  { value: "Montenegro", label: "Montenegro", region: "Europe" },
  { value: "Morocco", label: "Morocco", region: "Africa" },
  { value: "Mozambique", label: "Mozambique", region: "Africa" },
  { value: "Myanmar", label: "Myanmar", region: "Asia" },
  { value: "Namibia", label: "Namibia", region: "Africa" },
  { value: "Nauru", label: "Nauru", region: "Oceania" },
  { value: "Nepal", label: "Nepal", region: "Asia" },
  { value: "Netherlands", label: "Netherlands", region: "Europe" },
  { value: "New Zealand", label: "New Zealand", region: "Oceania" },
  { value: "Nicaragua", label: "Nicaragua", region: "North America" },
  { value: "Niger", label: "Niger", region: "Africa" },
  { value: "Nigeria", label: "Nigeria", region: "Africa" },
  { value: "North Korea", label: "North Korea", region: "Asia" },
  { value: "North Macedonia", label: "North Macedonia", region: "Europe" },
  { value: "Norway", label: "Norway", region: "Europe" },
  { value: "Oman", label: "Oman", region: "Middle East" },
  { value: "Pakistan", label: "Pakistan", region: "Asia" },
  { value: "Palau", label: "Palau", region: "Oceania" },
  { value: "Palestine", label: "Palestine", region: "Middle East" },
  { value: "Panama", label: "Panama", region: "North America" },
  { value: "Papua New Guinea", label: "Papua New Guinea", region: "Oceania" },
  { value: "Paraguay", label: "Paraguay", region: "South America" },
  { value: "Peru", label: "Peru", region: "South America" },
  { value: "Philippines", label: "Philippines", region: "Asia" },
  { value: "Poland", label: "Poland", region: "Europe" },
  { value: "Portugal", label: "Portugal", region: "Europe" },
  { value: "Qatar", label: "Qatar", region: "Middle East" },
  { value: "Romania", label: "Romania", region: "Europe" },
  { value: "Russia", label: "Russia", region: "Asia" },
  { value: "Rwanda", label: "Rwanda", region: "Africa" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", region: "North America" },
  { value: "Saint Lucia", label: "Saint Lucia", region: "North America" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", region: "North America" },
  { value: "Samoa", label: "Samoa", region: "Oceania" },
  { value: "San Marino", label: "San Marino", region: "Europe" },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe", region: "Africa" },
  { value: "Saudi Arabia", label: "Saudi Arabia", region: "Middle East" },
  { value: "Senegal", label: "Senegal", region: "Africa" },
  { value: "Serbia", label: "Serbia", region: "Europe" },
  { value: "Seychelles", label: "Seychelles", region: "Africa" },
  { value: "Sierra Leone", label: "Sierra Leone", region: "Africa" },
  { value: "Singapore", label: "Singapore", region: "Asia" },
  { value: "Slovakia", label: "Slovakia", region: "Europe" },
  { value: "Slovenia", label: "Slovenia", region: "Europe" },
  { value: "Solomon Islands", label: "Solomon Islands", region: "Oceania" },
  { value: "Somalia", label: "Somalia", region: "Africa" },
  { value: "South Africa", label: "South Africa", region: "Africa" },
  { value: "South Korea", label: "South Korea", region: "Asia" },
  { value: "South Sudan", label: "South Sudan", region: "Africa" },
  { value: "Spain", label: "Spain", region: "Europe" },
  { value: "Sri Lanka", label: "Sri Lanka", region: "Asia" },
  { value: "Sudan", label: "Sudan", region: "Africa" },
  { value: "Suriname", label: "Suriname", region: "South America" },
  { value: "Sweden", label: "Sweden", region: "Europe" },
  { value: "Switzerland", label: "Switzerland", region: "Europe" },
  { value: "Syria", label: "Syria", region: "Middle East" },
  { value: "Taiwan", label: "Taiwan", region: "Asia" },
  { value: "Tajikistan", label: "Tajikistan", region: "Asia" },
  { value: "Tanzania", label: "Tanzania", region: "Africa" },
  { value: "Thailand", label: "Thailand", region: "Asia" },
  { value: "Timor-Leste", label: "Timor-Leste", region: "Asia" },
  { value: "Togo", label: "Togo", region: "Africa" },
  { value: "Tonga", label: "Tonga", region: "Oceania" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago", region: "North America" },
  { value: "Tunisia", label: "Tunisia", region: "Africa" },
  { value: "Turkey", label: "Turkey", region: "Asia" },
  { value: "Turkmenistan", label: "Turkmenistan", region: "Asia" },
  { value: "Tuvalu", label: "Tuvalu", region: "Oceania" },
  { value: "Uganda", label: "Uganda", region: "Africa" },
  { value: "Ukraine", label: "Ukraine", region: "Europe" },
  { value: "United Arab Emirates", label: "United Arab Emirates", region: "Middle East" },
  { value: "United Kingdom", label: "United Kingdom", region: "Europe" },
  { value: "United States", label: "United States", region: "North America" },
  { value: "Uruguay", label: "Uruguay", region: "South America" },
  { value: "Uzbekistan", label: "Uzbekistan", region: "Asia" },
  { value: "Vanuatu", label: "Vanuatu", region: "Oceania" },
  { value: "Vatican City", label: "Vatican City", region: "Europe" },
  { value: "Venezuela", label: "Venezuela", region: "South America" },
  { value: "Vietnam", label: "Vietnam", region: "Asia" },
  { value: "Yemen", label: "Yemen", region: "Middle East" },
  { value: "Zambia", label: "Zambia", region: "Africa" },
  { value: "Zimbabwe", label: "Zimbabwe", region: "Africa" }
];

// Helper function to get region for a country
export const getRegionForCountry = (country: string): string => {
  const countryData = countries.find(c => c.value.toLowerCase() === country.toLowerCase());
  return countryData?.region || 'Global';
};
