// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xatnldmjhmazzidniyxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhdG5sZG1qaG1henppZG5peXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDIxNDYsImV4cCI6MjA2NTk3ODE0Nn0.LBn471hyJLPMvJ7ZTY2RPW48hczl5CBIaqRZxxl6X8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);